apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
    environment: production
  annotations:
    config: "https://my-config.com"
  spec:
    containers:
    - name: my-container
      image: my-image:tag
