apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-container
    image: my-image:tag
    resource:
      limits:
        cpu: "1" # 하나의 자원을 1이라고 하며 0.1이라고 할 시 10%를 사용한다는 뜻
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "500Mi"