apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: frontend
    image: frontend-image:tag
    ports:
    - containerPort: 80
  - name: backend
    image: frontend-image:tag
    ports:
    - containerPort: 8080